# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('hbversion', models.CharField(max_length=50)),
                ('portalversion', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
